### ISSUE TITLE
[feature request] Get video duration

### ISSUE THREAD

**Issue by wildsurfer** [Firelands128/photo_gallery#1]
It would be great if there will be a way to get video duration in minutes when you list all videos from the album.

**Comment by Firelands128** [comment]
I have release a new beta version ```0.2.1-beta```, which added video duration in milliseconds into ```Medium``` model's attributes. You can convert milliseconds to minutes as you want.

For media which ```MediumType``` is ```MediumType.image```, the duration attribute would be always 0.

**Comment by wildsurfer** [comment]
Awesome! Thanks!
