### ISSUE TITLE
[bug] Future<List<dynamic>> is not a subtype of Future<List<int>> in getThumbnail

### ISSUE THREAD

**Issue by lyio** [Firelands128/photo_gallery#16]
There seems to be a type mismatch when calling `getThumbnail` on a `Medium`. 

The method signature here is `Future<List<int>> getThumbnail()`, but it calls the static method `PhotoGallery.getThumbnail()` which returns a `Future<List<dynamic>>`. And with strict typing Dart cannot cast the `List<dynamic>` to a `List<int>`.

The solution could be to either return a `List<int>` from `PhotoGallery.getThumbnail` or cast the `List<dynamic>` to a `List<int>` manually before returning it.

I would favor the first suggestions, but I don't know what else could be returned from the native side, that would need to be `dynamic`.

**Comment by Firelands128** [comment]
It's solved by supporting null safety in release 1.0.0.
