### ISSUE TITLE
Thumbnail resolution is too low on Android

### ISSUE THREAD

**Issue by right7ctrl** [Firelands128/photo_gallery#18]
Is it possible to increase resolutions for thumbnail on android, if it is how can i do?

![photo_2021-04-08 15 55 51](https://user-images.githubusercontent.com/24523510/114030154-eb8d2b80-9882-11eb-8ef6-3230ce852715.jpeg)

**Comment by right7ctrl** [comment]
I solved for now, using flutter_image_compress and getting the high resolution image then decreasing resolution

**Comment by marcodecarolisidt** [comment]
Will this be fixed? both for video and pictures

**Comment by marcodecarolisidt** [comment]
@right7ctrl  It can be fixed by specifying width & height in the ThumbnailProvider

**Comment by marcodecarolisidt** [comment]
Although quality is still not as good as in iOs, it is written in the description. 

Hopefully will have highQuality also for android soon 🙏 

Thanks :)

**Comment by Firelands128** [comment]
Released version 1.0.1. It accepted ```highQuality``` parameter also for Android when getting image thumbnail or album thumbnail. Also, ```highQuality``` is default to ```true```. For more specific resolution, please specify width and height when try to get thumbnails.
