### ISSUE TITLE
Unable to list empty albums

### ISSUE THREAD

**Issue by ghensto** [Firelands128/photo_gallery#19]
Could add a parameter to allow us to get albums even if they are empty. For example:

``` 
PhotoGallery.listAlbums(
      mediumType: MediumType.video,
      hideIfEmpty: false,
    )
 ```

**Comment by Firelands128** [comment]
Added ```hideIfEmpty``` parameter to be able to show empty albums on version 1.0.1, but it's only available on iOS. I don't find the way to achieve this on Android.
