### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by fedeamura** [Firelands128/photo_gallery#25]
`
  The "newest" parameter do nothing. I got the same result with true or false.
  
  return widget.album.listMedia(
            newest: true,
  );
`

**Comment by HectorPalacio** [comment]
Hi, for sort the pics, you can use the .sort() method on this way:

imagenes.sort((a, b) => b.modifiedDate.compareTo(a.modifiedDate));

I sort the pics from the Date, but you can do it how do you want.

I hope help you.

**Comment by fedeamura** [comment]
yea, but if a get the info paginated i cant use this sort method

**Comment by fedeamura** [comment]
any news on this?

**Comment by Firelands128** [comment]
Sorry for the late reply. I have fix this bug in version 1.1.1.

**Comment by pablo-johnson** [comment]
Hi, I can still reproduce this issue on Android 11 with version 1.1.1.

I always get the oldest photo first when listing the media from an album, no matter if I specify the newest parameter as true or false.
