### ISSUE TITLE
listAlbums seems to be stuck ( or taking too long )

### ISSUE THREAD

**Issue by purezen** [Firelands128/photo_gallery#27]
I am using a Pixel 4a and the call `listAlbums(mediumType: MediumType.image)` seems to never finish

The call `listAlbums(mediumType: MediumType.image)` is working fine though

What could be causing it?

**Comment by DarkFighterLuke** [comment]
It can be because of this #30 

In fact, even with the example photo gallery app, it gets stuck if you have media in the root folder of your internal phone memory (`/sdcard`).

**Comment by Firelands128** [comment]
If this problem is because some images are stored in the root folder as @DarkFighterLuke said. It has fixed in version 1.1.0 by making album name nullable. You can try to upgrade the version of this package.
