### ISSUE TITLE
iOS: No way to retrieve user-friendly filename from Medium.

### ISSUE THREAD

**Issue by andrewrmiller** [Firelands128/photo_gallery#28]
I was hoping that I could get the IMG_XXX.JPG filename back from a Medium object but it doesn't look like it is exposed.

I'm building a synchronization engine and while I can use `medium.id` to generate unique filenames, I'd like to use the friendly names so that I match the behavior that the user sees when they share a photo with others via the iPhone.

**Comment by Firelands128** [comment]
Sorry for the late reply! I have added ```filename``` property of ```Medium``` in version 1.1.1.
