### ISSUE TITLE
Bug when album names are null

### ISSUE THREAD

**Issue by DarkFighterLuke** [Firelands128/photo_gallery#30]
When you retrieve album list, it will be stuck if you have some media in the root folder of your internal memory (`/sdcard`). 
This because of the name of that "album" is not recognized and the is set to null, causing an exception.

Please fix it, thanks.

**Comment by Firelands128** [comment]
Thank you for discovering this problem! But I change ```Album``` ```name``` property to nullable instead of giving an empty string to solve this problem. Because a nullable name have a more convenient way for users to realize more possibilities.
