### ISSUE TITLE
Has  crashed when i called  PhotoGallery.listAlbums method on android 9.1

### ISSUE THREAD

**Issue by washpan** [Firelands128/photo_gallery#38]
E/AndroidRuntime(20832): 	at android.os.AsyncTask$3.done(AsyncTask.java:355)
E/AndroidRuntime(20832): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(20832): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(20832): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(20832): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
E/AndroidRuntime(20832): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime(20832): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime(20832): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(20832): 	at java.lang.Thread.run(Thread.java:784)
E/AndroidRuntime(20832): Caused by: android.database.sqlite.SQLiteException: no such column: orientation (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT _id, _display_name, title, width, height, orientation, mime_type, duration, datetaken, date_modified FROM video ORDER BY datetaken DESC, date_modified DESC LIMIT 0 OFFSET 0, (OS error - 2:No such file or directory)
E/AndroidRuntime(20832): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
E/AndroidRuntime(20832): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime(20832): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
E/AndroidRuntime(20832): 	at android.content.ContentResolver.query(ContentResolver.java:816)
E/AndroidRuntime(20832): 	at android.content.ContentResolver.query(ContentResolver.java:766)
E/AndroidRuntime(20832): 	at android.content.ContentResolver.query(ContentResolver.java:717)
E/AndroidRuntime(20832): 	at com.morbit.photogallery.PhotoGalleryPlugin.listVideos(PhotoGalleryPlugin.kt:406)
E/AndroidRuntime(20832): 	at com.morbit.photogallery.PhotoGalleryPlugin.access$listVideos(PhotoGalleryPlugin.kt:25)
E/AndroidRuntime(20832): 	at com.morbit.photogallery.PhotoGalleryPlugin$onMethodCall$3.invoke(PhotoGalleryPlugin.kt:105)
E/AndroidRuntime(20832): 	at com.morbit.photogallery.PhotoGalleryPlugin$onMethodCall$3.invoke(PhotoGalleryPlugin.kt:25)
E/AndroidRuntime(20832): 	at com.morbit.photogallery.BackgroundAsyncTask.doInBackground(PhotoGalleryPlugin.kt:919)
E/AndroidRuntime(20832): 	at com.morbit.photogallery.BackgroundAsyncTask.doInBackground(PhotoGalleryPlugin.kt:913)
E/AndroidRuntime(20832): 	at android.os.AsyncTask$2.call(AsyncTask.java:334)
E/AndroidRuntime(20832): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(20832): 	... 5 more
I/Process (20832): Sending signal. PID: 20832 SIG: 9

android i try to modity PhotoGalleryPlugin.kt  android change the code as follow
val videoMetadataProjection = arrayOf(
            MediaStore.Video.Media._ID,
            MediaStore.Video.Media.DISPLAY_NAME,
            MediaStore.Video.Media.TITLE,
            MediaStore.Video.Media.WIDTH,
            MediaStore.Video.Media.HEIGHT,
//            MediaStore.Video.Media.ORIENTATION, this will be crash  on android 9.1 device honor 9 ,I have removed it. and work normal
            MediaStore.Video.Media.MIME_TYPE,
            MediaStore.Video.Media.DURATION,
            MediaStore.Video.Media.DATE_TAKEN,
            MediaStore.Video.Media.DATE_MODIFIED
        )

Could you modify that code at next  version fix it?

**Comment by ahammamlho** [comment]
the same

**Comment by Cryptorcheck** [comment]
the same

**Comment by Cryptorcheck** [comment]
the same

**Comment by Firelands128** [comment]
Solved by updating media query projection after version 1.2.0.
