### ISSUE TITLE
How to get both image & video types in listAlbums & Sorting in Pagination

### ISSUE THREAD

**Issue by rikai-trongpq** [Firelands128/photo_gallery#40]
I use `PhotoGallery.listAlbums` and `mediumType` prop required a object, not a List<MediumType>.  I expected result like that:
```
PhotoGallery.listAlbums(
        mediumType: [MediumType.video, MediumType.image],
      );
```
not
```
PhotoGallery.listAlbums(
        mediumType: MediumType.image, //or MediumType.video
      );
```
Because I wanna get all types of album. 
And how to sorting list media after I get a new pagination? Sorry my English is not good. I hope you understand.

**Comment by rikai-trongpq** [comment]
@Firelands128  Please help me..

**Comment by fn-19** [comment]
I have the same problem
Is your problem solved?

**Comment by Firelands128** [comment]
Support this feature by making "mediumType" to be optional to be able to allow fetch both types of media after version 2.0.0.
