### ISSUE TITLE
app destroy

### ISSUE THREAD

**Issue by LlMrc** [Firelands128/photo_gallery#46]
The application work fine with MEDIUMTYPE== IMAGE
 but when i try to run   MEDIUMTYPE == VIDEO, the app crash. 
The issue occurred when i try to open video album.
this the line who crash the app 
`void initAsync() async {
    MediaPage mediaPage = await widget.album.listMedia();
    setState(() {
      _media = mediaPage.items;
    });
  }`
 i can't display video list
please help.

**Comment by mzilaid** [comment]
I am also facing this issue

**Comment by tanveer1302** [comment]
Update to latest version. was facing same issue but updating to 1.1.1 fixed it

**Comment by Firelands128** [comment]
Please upgrade to a newer version.
