### ISSUE TITLE
[feature request] create thumbnail by passing video file path

### ISSUE THREAD

**Issue by msarkrish** [Firelands128/photo_gallery#5]
In my app i'm listing all the videos from storage by using your plugin. In some screens i need to display 1 or 2 videos. In that screen i need to display thumbnail for that 1 or 2 videos. So add thumbnail creation option by passing video path.

**Comment by Firelands128** [comment]
You can pass medium id to get thumbnail instead of video path, due to the limitation of accessing file path on iOS platform.

**Comment by msarkrish** [comment]
@Firelands128 I'm working in File Manager Like Application, In VideoPage I'm Displaying videos by calling ListAlbums method. But In Folder Screen, If user clicking Download directory, I need to display already downloaded videos with thumbnail. In that screen I have the path for download directory, and the path of available videos in Download directory. I don't know the medium id for that videos are available in the Download directory. So medium id is not helpful in this situation. so Please add method getting thumbnail by passing video path.

**Comment by Firelands128** [comment]
When user click on a specific directory, you should call ```listMedia``` method of that album to get the informations of media in that directory, which would provide medium id for you. You can refer to the example app of this plugin. Hope it helps.
