### ISSUE TITLE
project ':photo_gallery' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72

### ISSUE THREAD

**Issue by OssMess** [Firelands128/photo_gallery#50]
Getting this error

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':photo_gallery' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72

My build.gradle file on project level has
buildscript {
    ext.kotlin_version = '1.6.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

My build.gradle file on app level has
    compileSdkVersion 33

file:android/gradle/wrapper/gradle-wrapper.properties has
    distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip

fixed the issue by changing photo_library project gradle settings to match my setting above.

**Comment by Firelands128** [comment]
Upgraded gradle version after version 1.2.0.
