### ISSUE TITLE
App throw Sqlite exception on android 8.0 has no column orientation. How to fix this issues

### ISSUE THREAD

**Issue by AbdulRehmansofthub** [Firelands128/photo_gallery#56]
Caused by: android.database.sqlite.SQLiteException: no such column: orientation (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _id, _display_name, title, width, height, orientation, mime_type, duration, datetaken, date_modified FROM video ORDER BY datetaken DESC, date_modified DESC LIMIT 32 OFFSET 0
E/AndroidRuntime( 4886): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
E/AndroidRuntime( 4886): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime( 4886): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
E/AndroidRuntime( 4886): 	at android.content.ContentResolver.query(ContentResolver.java:809)
E/AndroidRuntime( 4886): 	at android.content.ContentResolver.query(ContentResolver.java:759)
E/AndroidRuntime( 4886): 	at android.content.ContentResolver.query(ContentResolver.java:717)
E/AndroidRuntime( 4886): 	at com.morbit.photogallery.PhotoGalleryPlugin.listVideos(PhotoGalleryPlugin.kt:406)
E/AndroidRuntime( 4886): 	at com.morbit.photogallery.PhotoGalleryPlugin.access$listVideos(PhotoGalleryPlugin.kt:25)
E/AndroidRuntime( 4886): 	at com.morbit.photogallery.PhotoGalleryPlugin$onMethodCall$3.invoke(PhotoGalleryPlugin.kt:105)
E/AndroidRuntime( 4886): 	at com.morbit.photogallery.PhotoGalleryPlugin$onMethodCall$3.invoke(PhotoGalleryPlugin.kt:102)
E/AndroidRuntime( 4886): 	at com.morbit.photogallery.BackgroundAsyncTask.doInBackground(PhotoGalleryPlugin.kt:919)
E/AndroidRuntime( 4886): 	at com.morbit.photogallery.BackgroundAsyncTask.doInBackground(PhotoGalleryPlugin.kt:913)
E/AndroidRuntime( 4886): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime( 4886): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 4886): 	... 4 more
I/Process ( 4886): Sending signal. PID: 4886 SIG: 9

**Comment by Firelands128** [comment]
Removed orientation column of video after version 1.2.0.
