### ISSUE TITLE
in media_page.dart line 22 type 'Null' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by OssMess** [Firelands128/photo_gallery#58]
I am running album.listMedia(take: limit), and receive an exception <type 'Null' is not a subtype of type 'int'> specifically in media_page.dart line 22.

In line 22:
  start: start = json['start'] //is returning null instead of an int

I fixed the bug just with
  start = json['start'] ?? 0

**Comment by sm-sayedi** [comment]
@OssMess The same exception occurs when `PhotoGallery.listAlbums(mediumType)` is called, which means when the `mediumType` is specified. Your solution worked for me too!

**Comment by Firelands128** [comment]
Solved in version 2.0.2
