### ISSUE TITLE
Album.listMedia hangs on Android 10

### ISSUE THREAD

**Issue by starikovvm** [Firelands128/photo_gallery#63]
The issue appeared after updating photo_gallery from 1.1.1 to 2.0.1. It worked well earlier.

```
    final List<Album> imageAlbums = await PhotoGallery.listAlbums(
      mediumType: MediumType.image,
    );
    try {
      final album = imageAlbums.firstWhere((album) => album.isAllAlbum);
      final mediaPage = await album.listMedia(
        take: min(_mediaPageSize, album.count),
        skip: 0,
      );  // <- this method hangs and never returns
    ...
```

Reproducable on devices and emulators using android 10 (API 29)

**Comment by Firelands128** [comment]
It would be solved after version 2.0.2. Please upgrade to latest version.

**Comment by Since55** [comment]
have same issue, version 2.0.2, 2.1.1. Reproducing only if passing [skip] parameter (Android 10)

**Comment by alfonsotesone** [comment]
Same problem here 😢 

Edit: I confirm that the problem only occurs when the skip parameter is present.

**Comment by dhpl** [comment]
any update, same problem here
