### ISSUE TITLE
run on ios

### ISSUE THREAD

**Issue by osama450** [Firelands128/photo_gallery#67]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
main.dart:1
Xcode build done.                                           462.5s
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/photo_gallery-2.1.0/lib/src/image_providers/album_thumbnail_provider.dart:28:59: Error: Type 'ImageDecoderCallback' not found.
album_thumbnail_provider.dart:28
Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by Firelands128** [comment]
Please upgrade your flutter version to 3.10 because ```ImageDecoderCallback``` is added in flutter 3.10.
