### ISSUE TITLE
listAlbums not showing empty albums

### ISSUE THREAD

**Issue by HoveringGoat** [Firelands128/photo_gallery#68]
Even when hideIfEmpty is false i'm not seeing empty albums. 

My steps to repro: programmatically create new album and add an image, remove image, album disappears from the list.

**Comment by Firelands128** [comment]
I cannot reproduce this issue, please provide more detail information (such as on which platform and version). Please note ```hideIfEmpty``` property is only available on iOS platform. I have added dart-doc to explain parameters usage in the future version. If you make sure this is an issue, feel free to reopen this issue.
